### ISSUE TITLE
Issues to Fix Before Final Product

### ISSUE THREAD

**Issue by RidhwanRama98** [Falskim/ppl-barokahqurban#2]
- Fix word 'Amanat' and move it to 'Donasi', adding 2 option : donation for the seller and for other person.
- Add more process status.
- Input for 'Quantity' must not be a word and must not accept value equal to 0 or negative numbers.

**Comment by Falskim** [comment]
- [x] Fix word 'Amanat' and move it to 'Donasi', adding 2 option : donation for the seller and for other person. [(2b7a7ad)](https://github.com/Falskim/ppl-barokahqurban/commit/2b7a7add1853c98d836fb7fd674716376670a3fd)
- [x] Add more process status. [(3b575fde)](https://github.com/Falskim/ppl-barokahqurban/commit/3b575fdec2c2304a4479a60e38c151d2b720c417)
- [x] Input for 'Quantity' must not be a word and must not accept value equal to 0 or negative numbers. [(dea9ece)](https://github.com/Falskim/ppl-barokahqurban/commit/dea9ece12d42a8f16a25285787e33e5c3113695el)

**Comment by Falskim** [comment]
Fixed and need to be tested
